### ISSUE TITLE
Connection pool for postgresql

### ISSUE THREAD

**Issue by to266** [eventually-rs/eventually-rs#136]
**Is your feature request related to a problem? Please describe.**
If `tokio-postgress` client loses the connection to the database (for example the postgres pod gets moved), the `EventStore`s are not able to recover from this even when the connection is possible to set up again.

**Describe the solution you'd like**
Use any kind of connection pooling. First search result seems to suggest https://crates.io/crates/deadpool-postgres 

**Describe alternatives you've considered**
 - Writing own postgresql-backed EventStore implementation, which internally uses the connection pool
 - Maybe some black-magic can be done with the [Connection](https://docs.rs/tokio-postgres/0.6.0/tokio_postgres/struct.Connection.html) that gets returned when establishing it in the first place?

**Additional context**

Hello! :raised_hands: 
We at https://luminovo.ai/ currently are using the open-sourced https://eventstore.com/ , but feel it either lacking, or simply not quite suitable for our use-case. `eventually-rs`, however, seems to be much better and even written in rust! Therefore, we are currently evaluating moving to `eventually` for our (currently in development) product! :smile: 

Not surprisingly, some feature requests might appear to keep track, but right now we expect to implement those features ourselves (and PR of course), so hopefully everyone ends up better! That being said, if something seems rather straightforward for you as the author(s), it might move things along quicker than necessarily waiting for our contributions.

So, a huge props for the library / framework, and a heads-up for potentially many more interactions :)

**Comment by ar3s3ru** [comment]
Hey @to266,
 
Thank you for opening the issue!

Connection pooling is something that I've meant to work on for some time, definitely a requirement to move `eventually` towards production-readiness.

I already researched some crates that could be used for this:
* [bb8], good configuration options, development seems pretty active but only using [Tokio]
* [mobc], good configuration options, but not much activity in the repository
* [deadpool], simple configuration (not necessarily a good thing), not tied to any executor in particular

I would probably go for [bb8], but I still haven't had any time to properly experiment all the choices and come up with an educated proposal.

Would you consider working on this feature? :smile:  

[bb8]: https://github.com/djc/bb8
[Tokio]: https://github.com/tokio-rs/tokio
[mobc]: https://github.com/importcjj/mobc
[deadpool]: https://github.com/bikeshedder/deadpool
